swagger: '2.0'
tags:
  - name: Swagger for Clean Text
get:
  description: None
responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Server Error
parameters:
  - name: file
    in: formData
    type: file
    required: false